export const browserCoreExamples = [
  "aeonsage browser status",
  "aeonsage browser start",
  "aeonsage browser stop",
  "aeonsage browser tabs",
  "aeonsage browser open https://example.com",
  "aeonsage browser focus abcd1234",
  "aeonsage browser close abcd1234",
  "aeonsage browser screenshot",
  "aeonsage browser screenshot --full-page",
  "aeonsage browser screenshot --ref 12",
  "aeonsage browser snapshot",
  "aeonsage browser snapshot --format aria --limit 200",
  "aeonsage browser snapshot --efficient",
  "aeonsage browser snapshot --labels",
];

export const browserActionExamples = [
  "aeonsage browser navigate https://example.com",
  "aeonsage browser resize 1280 720",
  "aeonsage browser click 12 --double",
  'aeonsage browser type 23 "hello" --submit',
  "aeonsage browser press Enter",
  "aeonsage browser hover 44",
  "aeonsage browser drag 10 11",
  "aeonsage browser select 9 OptionA OptionB",
  "aeonsage browser upload /tmp/file.pdf",
  'aeonsage browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "aeonsage browser dialog --accept",
  'aeonsage browser wait --text "Done"',
  "aeonsage browser evaluate --fn '(el) => el.textContent' --ref 7",
  "aeonsage browser console --level error",
  "aeonsage browser pdf",
];
