/**
 * Bot Diary - Daily Behavior Summary
 * 
 * Automatically generates daily summaries of bot activities
 * Creates shareable activity reports
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { homedir } from "node:os";
import { EventEmitter } from "node:events";

/** Activity Type */
export type ActivityType =
    | "task_completed"
    | "task_failed"
    | "message_sent"
    | "message_received"
    | "tool_used"
    | "error"
    | "wake"
    | "sleep";

/** Activity Entry */
export interface ActivityEntry {
    timestamp: string;
    type: ActivityType;
    description: string;
    metadata?: Record<string, unknown>;
}

/** Daily Summary */
export interface DailySummary {
    date: string;
    totalActivities: number;
    tasksCompleted: number;
    tasksFailed: number;
    messagesSent: number;
    messagesReceived: number;
    toolsUsed: string[];
    errors: number;
    uptime: number; // minutes
    highlights: string[];
}

/** Bot Diary Manager */
class BotDiaryManager extends EventEmitter {
    private static instance: BotDiaryManager;
    private activities: ActivityEntry[] = [];
    private diaryPath: string;
    private currentDate: string;

    private constructor() {
        super();
        this.diaryPath = path.join(homedir(), ".aeonsage", "diary");
        this.currentDate = this.getDateString();
        this.ensureDirectory();
        this.loadTodayActivities();
    }

    static getInstance(): BotDiaryManager {
        if (!BotDiaryManager.instance) {
            BotDiaryManager.instance = new BotDiaryManager();
        }
        return BotDiaryManager.instance;
    }

    /** Log Activity */
    logActivity(type: ActivityType, description: string, metadata?: Record<string, unknown>): void {
        const entry: ActivityEntry = {
            timestamp: new Date().toISOString(),
            type,
            description,
            metadata,
        };
        this.activities.push(entry);
        this.saveActivities();
        this.emit("activity-logged", entry);
    }

    /** Generate Daily Summary */
    generateSummary(date?: string): DailySummary {
        const targetDate = date ?? this.getDateString();
        const activities = this.getActivitiesForDate(targetDate);

        const toolsUsed = new Set<string>();
        const highlights: string[] = [];

        let tasksCompleted = 0;
        let tasksFailed = 0;
        let messagesSent = 0;
        let messagesReceived = 0;
        let errors = 0;

        for (const activity of activities) {
            switch (activity.type) {
                case "task_completed":
                    tasksCompleted++;
                    if (activity.metadata?.important) {
                        highlights.push(activity.description);
                    }
                    break;
                case "task_failed":
                    tasksFailed++;
                    break;
                case "message_sent":
                    messagesSent++;
                    break;
                case "message_received":
                    messagesReceived++;
                    break;
                case "tool_used":
                    if (activity.metadata?.tool) {
                        toolsUsed.add(activity.metadata.tool as string);
                    }
                    break;
                case "error":
                    errors++;
                    break;
            }
        }

        return {
            date: targetDate,
            totalActivities: activities.length,
            tasksCompleted,
            tasksFailed,
            messagesSent,
            messagesReceived,
            toolsUsed: Array.from(toolsUsed),
            errors,
            uptime: this.calculateUptime(activities),
            highlights,
        };
    }

    /** Generate Markdown Report */
    generateReport(date?: string): string {
        const summary = this.generateSummary(date);

        return `# Bot Diary - ${summary.date}

## Summary
- **Total Activities**: ${summary.totalActivities}
- **Tasks Completed**: ${summary.tasksCompleted}
- **Tasks Failed**: ${summary.tasksFailed}
- **Messages Sent**: ${summary.messagesSent}
- **Messages Received**: ${summary.messagesReceived}
- **Errors**: ${summary.errors}
- **Uptime**: ${summary.uptime} minutes

## Tools Used
${summary.toolsUsed.map(t => `- ${t}`).join("\n") || "- None"}

## Highlights
${summary.highlights.map(h => `- ${h}`).join("\n") || "- No highlights today"}

---
*Generated by AeonSage Bot Diary*
`;
    }

    /** Get Activities for Date */
    private getActivitiesForDate(date: string): ActivityEntry[] {
        const filePath = path.join(this.diaryPath, `${date}.json`);
        if (fs.existsSync(filePath)) {
            const content = fs.readFileSync(filePath, "utf-8");
            return JSON.parse(content);
        }
        return date === this.currentDate ? this.activities : [];
    }

    /** Calculate Uptime */
    private calculateUptime(activities: ActivityEntry[]): number {
        if (activities.length < 2) return 0;
        const first = new Date(activities[0].timestamp);
        const last = new Date(activities[activities.length - 1].timestamp);
        return Math.round((last.getTime() - first.getTime()) / 60000);
    }

    /** Save Activities */
    private saveActivities(): void {
        const filePath = path.join(this.diaryPath, `${this.currentDate}.json`);
        fs.writeFileSync(filePath, JSON.stringify(this.activities, null, 2));
    }

    /** Load Today's Activities */
    private loadTodayActivities(): void {
        const filePath = path.join(this.diaryPath, `${this.currentDate}.json`);
        if (fs.existsSync(filePath)) {
            const content = fs.readFileSync(filePath, "utf-8");
            this.activities = JSON.parse(content);
        }
    }

    /** Ensure Directory Exists */
    private ensureDirectory(): void {
        if (!fs.existsSync(this.diaryPath)) {
            fs.mkdirSync(this.diaryPath, { recursive: true });
        }
    }

    /** Get Date String */
    private getDateString(): string {
        return new Date().toISOString().split("T")[0];
    }
}

export const botDiary = BotDiaryManager.getInstance();
